### ISSUE TITLE
add support to different disks in Mediahelper class

### ISSUE THREAD

**Issue by ahmetsabri** [ahmedesa/laravel-api-tool-kit#32]

**Comment by rpsimao** [comment]
I've open a Pull request for this.
Awaiting approval

**Comment by ahmedesa** [comment]
This issue has been solved with tag [2.1.2](https://github.com/ahmedesa/laravel-api-tool-kit/releases/tag/2.1.2) thanks @rpsimao

**Comment by ahmedesa** [comment]
This issue has been solved with tag [2.1.2](https://github.com/ahmedesa/laravel-api-tool-kit/releases/tag/2.1.2) thanks @rpsimao

**Comment by ahmedesa** [comment]
This issue has been solved with tag [2.1.2](https://github.com/ahmedesa/laravel-api-tool-kit/releases/tag/2.1.2) thanks @rpsimao

**Comment by rpsimao** [comment]
Later today, I'll submit a PR for updating the official documentation.

**Comment by ahmedesa** [comment]
> Later today, I'll submit a PR for updating the official documentation.

I've already made some updates, but if you have any more changes in mind, feel free to add them.

**Comment by rpsimao** [comment]
I've made a PR just to change the comments on the default disk. It still mention the public disk fallback.
I'm gonna start using this package for an upcoming project. If I see any more valuable contribution, I'll PR.
Thanks for your work and share it with the community.
