### ISSUE TITLE
Add config featue for api/V1/frontend and api/V1/backend.

### ISSUE THREAD

**Issue by milanbeo** [ahmedesa/laravel-api-tool-kit#44]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by milanbeo** [comment]
I try
```
return [
    'groups_files_paths' => [
        'V1_Backend' => [
            GeneratorFilesType::MODEL => [
                'folder_path' => app_path('Models/V1/Backend'),
                'file_name' => '{ModelName}.php',
                'namespace' => 'App\Models\V1\Backend',
            ],
            GeneratorFilesType::CONTROLLER => [
                'folder_path' => app_path('Http/Controllers/V1/Backend'),
                'file_name' => '{ModelName}Controller.php',
                'namespace' => 'App\Http\Controllers\V1\Backend',
            ],
            GeneratorFilesType::RESOURCE => [
                'folder_path' => app_path('Http/Resources/V1/Backend/{ModelName}'),
                'file_name' => '{ModelName}Resource.php',
                'namespace' => "App\Http\Resources\V1\Backend\{ModelName}",
            ],
            GeneratorFilesType::ROUTES => [
                'folder_path' => base_path('routes/V1/Backend'),
                'file_name' => 'api.php',
                'namespace' => null,
            ],
            // Add other file types configurations as needed
        ],
        'V1_Frontend' => [
            GeneratorFilesType::MODEL => [
                'folder_path' => app_path('Models/V1/Frontend'),
                'file_name' => '{ModelName}.php',
                'namespace' => 'App\Models\V1\Frontend',
            ],
            GeneratorFilesType::CONTROLLER => [
                'folder_path' => app_path('Http/Controllers/V1/Frontend'),
                'file_name' => '{ModelName}Controller.php',
                'namespace' => 'App\Http\Controllers\V1\Frontend',
            ],
            GeneratorFilesType::RESOURCE => [
                'folder_path' => app_path('Http/Resources/V1/Frontend/{ModelName}'),
                'file_name' => '{ModelName}Resource.php',
                'namespace' => "App\Http\Resources\V1\Frontend\{ModelName}",
            ],
            GeneratorFilesType::ROUTES => [
                'folder_path' => base_path('routes/V1/Frontend'),
                'file_name' => 'api.php',
                'namespace' => null,
            ],
            // Add other file types configurations as needed
        ],
        // Keep the 'default' configuration as is for other general purposes
        'default' => [
            // Existing configurations...
        ],
    ],
    // Other configurations...
];
```
but not success

**Comment by ahmedesa** [comment]
Hi @milanbeo  !

To generate files for a specific group, use:

```bash
php artisan api:generate ModelName --all --group=V1_Backend
```

or for the 'V1_Frontend' group:

```bash
php artisan api:generate ModelName --all --group=V1_Frontend
```

If you're having issues, could you share more details on the error? and I'll be happy to help!

**Comment by milanbeo** [comment]
I used next config
`
 'V1_Backend' => [
            GeneratorFilesType::MODEL => [
                'folder_path' => app_path('Models'),
                'file_name' => '{ModelName}.php',
                'namespace' => 'App\Models',
            ],
            GeneratorFilesType::FACTORY => [
                'folder_path' => database_path('factories'),
                'file_name' => '{ModelName}Factory.php',
                'namespace' => 'Database\Factories',
            ],
            GeneratorFilesType::SEEDER => [
                'folder_path' => database_path('seeders'),
                'file_name' => '{ModelName}Seeder.php',
                'namespace' => 'Database\Seeders',
            ],
            GeneratorFilesType::CONTROLLER => [
                'folder_path' => app_path('Http/Controllers/V1/Backend'),
                'file_name' => '{ModelName}Controller.php',
                'namespace' => 'App\Http\Controllers\V1\Backend',
            ],
            GeneratorFilesType::RESOURCE => [
                'folder_path' => app_path('Http/Resources/V1/Backend/{ModelName}'),
                'file_name' => '{ModelName}Resource.php',
                'namespace' => "App\Http\Resources\V1\Backend\{ModelName}",
            ],
            GeneratorFilesType::ROUTES => [
                'folder_path' => base_path('routes/V1/Backend'),
                'file_name' => 'api.php',
                'namespace' => null,
            ],
`
When I run 
`php artisan api:generate User  --group=V1_backend `
Result is: The path group you entered is not valid.

**Comment by ahmedesa** [comment]
It looks like the issue is due to case sensitivity in the group name. In your config, the group is named "V1_Backend," but in your command, you used "V1_backend."

Try running the command with the correct case:

```bash
php artisan api:generate User --all --group=V1_Backend
```
Let me know if that resolves the problem!

**Comment by milanbeo** [comment]
No, this not resolve. Error is:
`Essa\APIToolKit\Generator\Exception\ConfigNotFoundException

  Base URL prefix not found for route group: V1_Backend

  at vendor\essa\api-tool-kit\src\Generator\Configs\PathConfigHandler.php:106
    102▕
    103▕         $baseURL = $routeGroupBaseURLs[$pathGroupName] ?? null;
    104▕
    105▕         if (null === $baseURL) {
  ➜ 106▕             throw new ConfigNotFoundException("Base URL prefix not found for route group: {$pathGroupName}");    107▕         }
    108▕
    109▕         return $baseURL;
    110▕     }

  1   vendor\essa\api-tool-kit\src\Generator\Helpers\StubVariablesProvider.php:57
      Essa\APIToolKit\Generator\Configs\PathConfigHandler::getBaseUrlPrefixForGroup("V1_Backend")

  2   vendor\essa\api-tool-kit\src\Generator\Helpers\StubVariablesProvider.php:24
      Essa\APIToolKit\Generator\Helpers\StubVariablesProvider::getBaseUrlPrefix("V1_Backend")``

**Comment by ahmedesa** [comment]
Got it! The issue is that you need to include the route group prefix in the configuration. In your config file, add the route prefixes for your groups under 'groups_url_prefixes.' Here's an example:

```php
'groups_url_prefixes' => [
    'V1_Backend' => '/api/backend',
    'V1_Frontend' => '/api/frontend',
],
```

Feel free to customize the prefixes according to your needs.
