### ISSUE TITLE
Exception Handler no longer works in laravel 11

### ISSUE THREAD

**Issue by bgmastermind** [ahmedesa/laravel-api-tool-kit#46]
**Describe the bug**
Exception Handler no longer works in laravel 11. Actually I never tried your package in laravel 10, but u guess it works there, because the changes are in 11.

**To Reproduce**
1. Create any request that fails validation

**Expected behavior**
To receive the expected json

**Additional context**
I've followed the install instructions by creating app\Exceptions\Handler.php 
and adding there
```
namespace App\Exceptions;

use Essa\APIToolKit\Exceptions\Handler as APIHandler;

class Handler extends APIHandler
{
}
```
But when i test i get the default laravel error instead of the expected package error
This is what i get as a response
```
{
    "message": "The email has already been taken. (and 1 more error)",
    "errors": {
        "email": [
            "The email has already been taken."
        ],
        "terms": [
            "The terms field is required."
        ]
    }
}
```

**Comment by ahmedesa** [comment]
Yes, you're correct. In Laravel 11, exceptions are handled differently, and the traditional `Handler` class is no longer used. Instead, you can bind the exception handler in your `AppServiceProvider` like this:

```php
<?php

namespace App\Providers;

use Essa\APIToolKit\Exceptions\Handler;
use Illuminate\Contracts\Debug\ExceptionHandler;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->bind(ExceptionHandler::class, Handler::class); // add this line 
    }
}
```

I'll make sure to update the documentation for Laravel 11 users. Thank you for reporting this issue!
