### ISSUE TITLE
When using HasManyThrough and dynamicPaginate - wrong (duplicate) records are returned

### ISSUE THREAD

**Issue by bgmastermind** [ahmedesa/laravel-api-tool-kit#47]
**Describe the bug**
If you take the laravel docs example https://laravel.com/docs/11.x/eloquent-relationships#has-many-through
and do 
`$project->deployments()->useFilters()->dynamicPaginate()`;

Then all the results will show only the first deployment. The count is correct.
If I change it to 
`$project->deployments()->useFilters()->get()`;  
then then it works correctly.

I've also tested and it works correctly for a different hasMany relation.

So I tried to find a fix and I found that if I change
```
$results = ($total = $this->toBase()->getCountForPagination())
                ? $this->forPage($page, $perPage)->get(['*'])
                : $this->model->newCollection();
```
to
```
$results = ($total = $this->toBase()->getCountForPagination())
                ? $this->model->forPage($page, $perPage)->get(['*'])
                : $this->model->newCollection();
```
in MacroServiceProvider.php then issue is fixed, but it brakes the hasMany relation. It starts to show all rows instead of the related, but counts them correctly.

**To Reproduce**
replicate 
https://laravel.com/docs/11.x/eloquent-relationships#has-many-through
and do 
`$project->deployments()->useFilters()->dynamicPaginate()`;

**Expected behavior**
To show expected records

**Comment by ahmedesa** [comment]
does it work with normal build-in pagination?

**Comment by bgmastermind** [comment]
yes it works as expected
