### ISSUE TITLE
Can the stub be published?

### ISSUE THREAD

**Issue by tonitomystery** [ahmedesa/laravel-api-tool-kit#48]
Is there a way to publish the stubs? I need to add the swagger documentation to the controller

**Comment by ahmedesa** [comment]
Hey @tonitomystery ,

Thanks for your feedback! We've just added a new feature to support publishing the stubs, In version 2.1.6, you can now publish the stubs, Just run:

```sh
php artisan vendor:publish --provider="Essa\APIToolKit\APIToolKitServiceProvider" --tag="stubs"
```

This will put the stubs in your project's `/stubs/api-tool-kit` directory so you can customize them.

Let me know if you have any questions!
